apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
- ../../base

patches:
  - target:
      kind: Deployment
      name: octopetshop-web-deployment
    path: octopetshop-web-deployment.yaml
  - target: 
      kind: Ingress
      name: octopetshop-ingress
    path: octopetshop-ingress.yaml
  - target:
      kind: Service
      name: octopetshop-web-cluster-ip-service
    path: octopetshop-web-cluster-ip-service.yaml
