apiVersion: v1
kind: Service
metadata:
  name: octopetshop-sqlserver-cluster-ip-service
  codefresh.io/product: octopetshop
spec:
  type: ClusterIP
  selector:
    component: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
