apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: octopetshop-test
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Automatically use all clusters defined within ArgoCD
  template:
    metadata:
      name: '{{.name}}-octopetshop-test'
      annotations:
        codefresh.io/product: octopetshop-{{.name}}      
    spec:
      project: default
      source:
        repoURL: https://github.com/twerthi/OctoPetShop.git
        targetRevision: HEAD
        path: k8s/kustomize/deployment/overlays/Test
      destination:
        server: '{{.server}}'
        namespace: test
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=false
        - CreateNamespace=true
