name: Codefresh Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
         export PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER
         echo "It is $PACKAGE_VERSION"
         jq --arg version $PACKAGE_VERSION '.AppSettings.AppVersion = "" + $version + ""' OctopusSamples.OctoPetShop.Web/appsettings.json > tmp.json && mv tmp.json OctopusSamples.OctoPetShop.Web/appsettings.json
         jq '.AppSettings.AppVersion' OctopusSamples.OctoPetShop.Web/appsettings.json
         echo "GitHub ref name: ${{ github.ref_name }}"
         echo "LATEST_PR=$(gh pr list --state merged --json mergedAt,headRefName --jq 'sort_by(.mergedAt) | reverse | .[0].headRefName')" >> $GITHUB_ENV

    # Display the last pr branch name and version
    - name: Display Last PR Branch Name and Version
      run: |
        echo "Last PR Branch Name: ${{ env.LATEST_PR }}"
        echo "Package Version: ${{ env.PACKAGE_VERSION }}"

    # Login to dockerhub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    # Gather commit messages to pass to JIRA_MESSAGE
    - name: Gather commit messages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        $commitMessages = @()
        $pr = (gh pr view fix-cat-entry --json commits | ConvertFrom-JSON)
        foreach ($commit in $pr.commits)
        {
          $commitMessages += @($commit.messageHeadline)
        }

        $commitString = $commitMessages -join "`n"

        Write-Host "CommitString: $commitString"

        # Save to environment variable
        echo "COMMIT_MESSAGES=$($commitString)" >> $GITHUB_ENV

    # Display the last pr branch name and version
    - name: Display Last PR commits
      run: |
        echo "Commits: ${{ env.COMMIT_MESSAGES }}"

    # Build docker images
    - name: Build Docker Images
      run: |
        docker build -t twerthi/octopetshop-database:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.Database/Dockerfile OctopusSamples.OctoPetShop.Database
        docker build -t twerthi/octopetshop-productservice:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.ProductService/Dockerfile OctopusSamples.OctoPetShop.ProductService
        docker build -t twerthi/octopetshop-shoppingcartservice:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.ShoppingCartService/Dockerfile OctopusSamples.OctoPetShop.ShoppingCartService
        docker build -t twerthi/octopetshop-web:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.Web/Dockerfile OctopusSamples.OctoPetShop.Web
        docker push twerthi/octopetshop-database:${{ env.PACKAGE_VERSION }}
        docker push twerthi/octopetshop-productservice:${{ env.PACKAGE_VERSION }}
        docker push twerthi/octopetshop-shoppingcartservice:${{ env.PACKAGE_VERSION }}
        docker push twerthi/octopetshop-web:${{ env.PACKAGE_VERSION }}

    # Push information to Codefresh
    - name: Codefresh image reporter - Database
      with:
        # Name of runtime to implement the enrichment
        CF_RUNTIME_NAME: 'codefresh-local'

        # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_API_KEY: ${{ secrets.CODEFRESH_TOKEN }}

        # Name of Container registry integration
        CF_CONTAINER_REGISTRY_INTEGRATION: 'twerthi-dockerhub'

        # The git branch which is related for the commit
        #CF_GIT_BRANCH: ${{ github.ref_name }}
        CF_GIT_BRANCH: ${{ env.LATEST_PR }}

        # Image path to enrich 
        CF_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/octopetshop-database:${{ env.PACKAGE_VERSION }}

        # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_GITHUB_TOKEN: ${{ inputs.github_codefresh_token }}    

        # # Name of Jira integration
        CF_ISSUE_TRACKING_INTEGRATION: 'twerthi-jira' 

        # # String starting with the issue ID to associate with image
        CF_JIRA_MESSAGE: "${{ env.COMMIT_MESSAGES }}"

        # # Jira project filter
        CF_JIRA_PROJECT_PREFIX: "CTPTSHP"
      uses: codefresh-io/codefresh-report-image@latest

    - name: Codefresh image reporter - Web
      with:
        # Name of runtime to implement the enrichment
        CF_RUNTIME_NAME: 'codefresh-local'

        # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_API_KEY: ${{ secrets.CODEFRESH_TOKEN }}

        # Name of Container registry integration
        CF_CONTAINER_REGISTRY_INTEGRATION: 'twerthi-dockerhub'

        # The git branch which is related for the commit
        #CF_GIT_BRANCH: ${{ github.ref_name }}
        CF_GIT_BRANCH: ${{ env.LATEST_PR }}

        # Image path to enrich 
        CF_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/octopetshop-web:${{ env.PACKAGE_VERSION }}

        # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_GITHUB_TOKEN: ${{ inputs.github_codefresh_token }}    

        # # Name of Jira integration
        CF_ISSUE_TRACKING_INTEGRATION: 'twerthi-jira' 

        # # String starting with the issue ID to associate with image
        CF_JIRA_MESSAGE: "${{ env.COMMIT_MESSAGES }}"

        # # Jira project filter
        CF_JIRA_PROJECT_PREFIX: "CTPTSHP"
      uses: codefresh-io/codefresh-report-image@latest 

    - name: Codefresh image reporter - ProductService
      with:
        # Name of runtime to implement the enrichment
        CF_RUNTIME_NAME: 'codefresh-local'

        # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_API_KEY: ${{ secrets.CODEFRESH_TOKEN }}

        # Name of Container registry integration
        CF_CONTAINER_REGISTRY_INTEGRATION: 'twerthi-dockerhub'

        # The git branch which is related for the commit
        #CF_GIT_BRANCH: ${{ github.ref_name }}
        CF_GIT_BRANCH: ${{ env.LATEST_PR }}

        # Image path to enrich 
        CF_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/octopetshop-productservice:${{ env.PACKAGE_VERSION }}

        # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_GITHUB_TOKEN: ${{ inputs.github_codefresh_token }}    

        # # Name of Jira integration
        CF_ISSUE_TRACKING_INTEGRATION: 'twerthi-jira' 

        # # String starting with the issue ID to associate with image
        CF_JIRA_MESSAGE: "${{ env.COMMIT_MESSAGES }}"

        # # Jira project filter
        CF_JIRA_PROJECT_PREFIX: "CTPTSHP"
      uses: codefresh-io/codefresh-report-image@latest            

    - name: Codefresh image reporter - ShoppingCartService
      with:
        # Name of runtime to implement the enrichment
        CF_RUNTIME_NAME: 'codefresh-local'

        # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_API_KEY: ${{ secrets.CODEFRESH_TOKEN }}

        # Name of Container registry integration
        CF_CONTAINER_REGISTRY_INTEGRATION: 'twerthi-dockerhub'

        # The git branch which is related for the commit
        #CF_GIT_BRANCH: ${{ github.ref_name }}
        CF_GIT_BRANCH: ${{ env.LATEST_PR }}

        # Image path to enrich 
        CF_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/octopetshop-shoppingcartservice:${{ env.PACKAGE_VERSION }}

        # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_GITHUB_TOKEN: ${{ inputs.github_codefresh_token }}    

        # # Name of Jira integration
        CF_ISSUE_TRACKING_INTEGRATION: 'twerthi-jira' 

        # # String starting with the issue ID to associate with image
        CF_JIRA_MESSAGE: "${{ env.COMMIT_MESSAGES }}"

        # # Jira project filter
        CF_JIRA_PROJECT_PREFIX: "OC"
      uses: codefresh-io/codefresh-report-image@latest                  
