name: Codefresh Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    # Login to dockerhub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    # Build docker images
    - name: Build Docker Images
      run: |
        docker build -t twerthi/octopetshop-database:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.Database/Dockerfile OctopusSamples.OctoPetShop.Database
        docker build -t twerthi/octopetshop-productservice:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.ProductService/Dockerfile OctopusSamples.OctoPetShop.ProductService
        docker build -t twerthi/octopetshop-shoppingcartservice:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.ShoppingCartService/Dockerfile OctopusSamples.OctoPetShop.ShoppingCartService
        docker build -t twerthi/octopetshop-web:${{ env.PACKAGE_VERSION }} -f OctopusSamples.OctoPetShop.Web/Dockerfile OctopusSamples.OctoPetShop.Web
        docker push twerthi/octopetshop-database:${{ env.PACKAGE_VERSION }}
        docker push twerthi/octopetshop-productservice:${{ env.PACKAGE_VERSION }}
        docker push twerthi/octopetshop-shoppingcartservice:${{ env.PACKAGE_VERSION }}
        docker push twerthi/octopetshop-web:${{ env.PACKAGE_VERSION }}
